// Generated by LispyScript v0.3.6
var fs = require("fs"),
    ls = require("../lib/ls");
require.extensions[".ls"] = function(module,filename) {
    var code = fs.readFileSync(filename,"utf8");
    return module._compile(ls._compile(code,filename),filename);
};
require("../src/macros");
