// Generated by LispyScript v1.0.0
var fs = require("fs");
var http = require("http");
var requestHandler = function(request,response) {
    return (function() {
        var filename = null;
        ((request.url === "/") ?
            filename = "index.html" :
            filename = request.url.substr(1));
        response.setHeader("Content-Type","text/html");
        var next = null;
        var ___curr = 0;
        var ___actions = new Array(function() {
            return fs.exists(filename,next());
        },function(exists) {
            return (exists ?
                fs.readFile(filename,"utf8",next()) :
                response.end("File Not Found"));
        },function(err,data) {
            return (err ?
                response.end("Internal Server Error") :
                response.end(data));
        });
        next = function() {
            var ne = ___actions[___curr++];
            return (ne ?
                ne :
                (function(){throw "Call to (next) beyond sequence.";})());
        };
        return next()();
    })();
};
var server = http.createServer(requestHandler);
server.listen(3000,"127.0.0.1");
console.log("Server running at http://127.0.0.1:3000/");
